version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: auth-api-db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"